/*
 * HeatingElement_Private.h
 *
 *  Created on: Oct 6, 2022
 *      Author: LENOVO.SXM10
 */

#ifndef HAL_HEATINGELEMENT_HEATINGELEMENT_PRIVATE_H_
#define HAL_HEATINGELEMENT_HEATINGELEMENT_PRIVATE_H_



#endif /* HAL_HEATINGELEMENT_HEATINGELEMENT_PRIVATE_H_ */
