/*
 * HeatingElement_Configure.h
 *
 *  Created on: Oct 6, 2022
 *      Author: LENOVO.SXM10
 */

#ifndef HAL_HEATINGELEMENT_HEATINGELEMENT_CONFIGURE_H_
#define HAL_HEATINGELEMENT_HEATINGELEMENT_CONFIGURE_H_

#define HEATING_ELEMENT_PIN				PC2_PIN

#endif /* HAL_HEATINGELEMENT_HEATINGELEMENT_CONFIGURE_H_ */
